apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      container:
        - name: client
          image: nranjan2004/multi-client
          ports: 
            - containerPort: 3000
      
    
    